version: "3"

services:
  api:
    container_name: exam_api
    build:
      context: ./api
    image: exam_api
    networks:
      mynetwork:
        aliases:
          - api
  perm:
    container_name: exam_perm
    build:
      context: ./perm
    environment:
        - LOG=1
    image: exam_perm
    depends_on:
      api:
        condition: service_healthy
    networks:
      mynetwork:
        aliases:
          - perm
    volumes:
      - ./logs:/usr/src/app/logs

  auth:
    container_name: exam_auth
    build:
      context: ./auth
    environment: 
        - LOG=1
    image: exam_auth
    depends_on:
      api:
        condition: service_healthy
    networks:
      mynetwork:
        aliases:
          - auth
    volumes:
      - ./logs:/usr/src/app/logs

  sentiment:
    container_name: exam_sentiment
    build:
      context: ./sentiment
    environment:
        - LOG=1
    image: exam_sentiment
    depends_on:
      api:
        condition: service_healthy
    networks:
      mynetwork:
        aliases:
          - sentiment
    volumes:
      - ./logs:/usr/src/app/logs
networks:
  mynetwork:

